### ISSUE TITLE
is broke

### ISSUE THREAD

**Issue by polkabunny** [redbrick/static-site#235] opened 2017-10-05 13:24 UTC
14:04:29 <@werepints> Everyone should go look at the cool new posts on redbrick.dcu.ie
...
14:04:58 < carri> your website sucks
14:05:05 <@werepints> carri: you suck
14:05:13 < carri> | events | contact | Call for Talks |
14:05:19 < carri> WHY U MIX CAPS :(
14:05:21 < mincebot> carri: 'You', scuttero. 'You'.
14:05:49 <@werepints> carri: open a PR
14:05:51 <@werepints> :P
...
14:18:09 < carri> https://www.redbrick.dcu.ie/about/contact/pints
14:18:10 < mrs_ghoul> are you going ickyd
14:18:12 < carri> so broke
14:18:19 < carri> I tried to use this to tell you it was broke
14:18:22 < carri> but it's broke
14:18:25 < ickyd> lol
14:18:27 < carri> so ...
14:18:33 < ickyd> good way to stop bug reports coming through
14:18:38 < ickyd> put a bug ont he bug report page
14:18:42 < carri> "Contact" 
14:18:43 < carri> lolno
14:18:49 < ickyd> 'no bugs reported since app launch!"
14:19:05 < ickyd> i probably would go if it was in town
14:19:11 < ickyd> no thats a lie
14:19:27 < plkageist> wow that is terrible
14:19:29 < dregula> NO BUGS IN MY TIME!
14:19:32 < plkageist> butlrexam: fix it
14:19:44 <@butlrexam> not my jb
14:19:46 < carri> how will they know it's broken
14:19:50 <@butlrexam> jerb*
14:19:53 < carri> if the contact form doesn't work D: 
14:19:57 < plkageist> butlrexam: fix it fix it fix it fix it
14:20:09 < plkageist> Why does it cover up your inputs
14:20:18 < gamma> That contact form is so horribly designed
14:20:21 < gamma> I don't understand
14:20:39 < carri> It also seems to keep track of your pages
14:20:45 < plkageist> It doesn't highlight errors in an understandable way
14:20:46 < carri> i can't even look at it anymore 
14:20:52 < plkageist> Recaptcha shits itself
14:21:56 <@butlrexam> plkageist: not my jerb
14:22:02 <@werepints> github.com/redbrick/static-site/
14:22:10 < plkageist> I'm raising an issue
14:22:14 < plkageist> I'm calling it is broke
14:22:24 < plkageist> And the body is just gonna be from #lobby
14:22:33 < carri> grand
14:22:40 < carri> tell him we said his website sucks
14:23:47 < ickyd> i like the way it has the input in the input boxes but it doesnt hide the placeholder when they are populated
14:23:58 < carri> I don't like it.
14:24:01 < ickyd> is this the new meta in UX
14:24:05 < carri> the . was a full stop

**Comment by lochlannach-beag** [comment] 2017-10-05 13:27
Fix please.

**Comment by butlerx** [comment] 2017-10-05 13:33
closing duplicate of #228

**Closed by butlerx** 2017-10-05 13:33 UTC
